### ISSUE TITLE
Manual outdated

### ISSUE THREAD

**Issue by foehnwind** [rufletch/p63-HBC-diff#2]
Dear authors, thanks for making available this pipeline! However, I notice that there have been several updates for the package `scone`'s API, which makes the current manual incompatible. 

For example, in `oeHBCdiff_norm.R`, 
```{r}
scone(counts, imputation=list(none=impute_null), impute_args=list(0), return_norm="in_memory", scaling=list(none=identity, fq=FQT_FN, deseq=DESEQ_FN, tmm=TMM_FN), k_ruv=3, k_qc=3, ruv_negcon=hk, qc=as.matrix(qc), adjust_bio="yes", bio=expt, adjust_batch="yes", batch=batch,run=TRUE, evaluate=TRUE, eval_negcon=cc, eval_poscon=del, eval_kclust = 10:12)
```

will result in an error
```
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘scone’ for signature ‘"matrix"’
```

Because the current version (1.2.0) `scone` requires an `SconeExperiment` object as `x` in function `scone`. Besides, the parameters `bio`, `qc`, `ruv_negcon`, `eval_negcon`, `eval_poscon` have been moved into the `SconeExperiment` construct, and `ruv_negcon`, `eval_negcon`, `eval_poscon` renamed as `negcon_eval`, `negcon_ruv`, `poscon`. 

Could you please help check and update your scripts? Thanks.

**Comment by rufletch** [comment]
Hello,
Thanks for your feedback. This repository serves as a record of our analysis for the publication cited in the README, which refers to specific version numbers of the software packages that we used. We do not plan to update the code in this repository because it will be out of sync with the publication. However, we will update the README to include the software version numbers.

If you are looking for a more updated version of the general workflow for scRNA-seq data that uses SCONE and RSEC/clusterExperiment, please see [Perraudeau et al. (2017)](https://f1000research.com/articles/6-1158/v1). There is also a github [repo](https://github.com/fperraudeau/singlecellworkflow) as well.
