### ISSUE TITLE
Missing clusters assignments

### ISSUE THREAD

**Issue by zouter** [rufletch/p63-HBC-diff#3]
Hi, thank you for this repo

Is it normal that some cells do not have a cluster label in ref/oeHBCdiff_clusterLabels.txt ? Clusters 13 and 6 are probably missing..

Thanks!

**Comment by diyadas** [comment]
Hi Wouter,

There are a couple issues and an error (thanks for catching it!):
1. unclustered cells (these are marked as -1s by the clusterExperiment package) - these are cells that do not fit well in any cluster. I would not use them in any cluster-based analysis. I believe that @kstreet13 has updated slingshot so that you could project them onto a lineage after the trajectories are constructed, though.
2. small cell clusters - we did not include clusters with fewer than ten cells in our analyses.
3. the clusterKey was labeled in numerical order after dropping the small cell clusters, not by the levels of the factor which were used for the clusterLabels text file.

I've updated the clusterKey.md file to refer to the factor levels in clusterLabels.txt. Sorry for the confusion!

**Comment by kstreet13** [comment]
re: 1. Yes, we recently added a `predict` function that does exactly that!
